(ns analitica.sync.plan
  "V4 Sync Plan Generator — Phase 3.
   Pure planning logic (no I/O except persist-plan! which writes to the registry).
   Produces a vector of task descriptors in topological order (ingest before materialize)."
  (:require [analitica.sync.registry :as registry]
            [analitica.util.time :as time]
            [analitica.ingest :as ingest]
            [analitica.materialize :as materialize]))

;; ---------------------------------------------------------------------------
;; Compatibility matrix
;; ---------------------------------------------------------------------------

;; Which (marketplace, entity-type) pairs are valid.
;; Based on ingest!/materialize! source analysis:
;;   WB:   sales, orders, finance, stocks, prices, stats, storage, regions
;;   Ozon: sales, orders, finance, stocks, prices, stats, cashflow
;;   YM:   sales, orders, finance, stocks, prices, stats
(def ^:private mp-entity-matrix
  {:wb   #{:sales :orders :finance :stocks :prices :stats :storage :regions}
   :ozon #{:sales :orders :finance :stocks :prices :stats :cashflow}
   :ym   #{:sales :orders :finance :stocks :prices :stats}})

(def ^:private all-marketplaces [:wb :ozon :ym])

;; All entity types that appear in any marketplace
(def ^:private all-entity-types
  (into #{} (mapcat val mp-entity-matrix)))

;; ---------------------------------------------------------------------------
;; Internal helpers
;; ---------------------------------------------------------------------------

(defn- compatible?
  "Returns true when (mp, entity-type) is a valid combination."
  [mp entity-type]
  (contains? (get mp-entity-matrix mp #{}) entity-type))

(defn- task-id
  "Build canonical task ID string: '<run-id>/<mp>/<entity>/<phase>'.

   The run-id prefix is what makes IDs unique across runs — without it
   the second invocation hits a sync_tasks PRIMARY KEY collision."
  [run-id mp entity-type phase]
  (str run-id "/" (name mp) "/" (name entity-type) "/" (name phase)))

(defn- make-task-pair
  "Return [ingest-descriptor materialize-descriptor] for one (mp, entity-type) pair."
  [run-id mp entity-type period-from period-to]
  (let [ingest-id  (task-id run-id mp entity-type :ingest)
        mat-id     (task-id run-id mp entity-type :materialize)
        period-vec [period-from period-to]]
    [{:id           ingest-id
      :run-id       run-id
      :marketplace  mp
      :entity-type  entity-type
      :phase        :ingest
      :period-from  period-from
      :period-to    period-to
      :depends-on   []
      :thunk        #(or (ingest/ingest! entity-type
                                         :marketplace mp
                                         :period period-vec)
                         0)}
     {:id           mat-id
      :run-id       run-id
      :marketplace  mp
      :entity-type  entity-type
      :phase        :materialize
      :period-from  period-from
      :period-to    period-to
      :depends-on   [ingest-id]
      :thunk        #(or (materialize/materialize! entity-type
                                                   :marketplace mp
                                                   :period period-vec)
                         0)}]))

;; ---------------------------------------------------------------------------
;; Public API
;; ---------------------------------------------------------------------------

(defn expand-plan
  "Generate a vector of task descriptors for one user-triggered run.

   Args (kwargs):
     :run-id      — string, generated by caller (e.g. UUID-string)
     :what        — :all | :sales | :orders | :finance | :stocks | :prices |
                    :storage | :stats | :regions | :cashflow | ...
     :marketplace — :all | :wb | :ozon | :ym | nil (defaults :wb if not :all)
     :period      — keyword like :last-30-days, OR a [from to] vector,
                    OR a {:from :to} map. Stored as :period-from/:period-to
                    on each task row.

   Returns: vector of task descriptors in topological order (all ingest first,
   then all materialize). Each descriptor:
     {:id           string  e.g. \"wb/sales/ingest\"
      :run-id       string
      :marketplace  keyword
      :entity-type  keyword
      :phase        :ingest | :materialize
      :period-from  iso-date string
      :period-to    iso-date string
      :depends-on   [task-id ...]
      :thunk        () → items-count}"
  [& {:keys [run-id what marketplace period]
      :or   {period :last-30-days}}]
  (let [;; Resolve period to [from to] strings
        [period-from period-to] (time/resolve-period (or period :last-30-days))
        ;; Determine which marketplaces to fan out to
        mps   (if (or (nil? marketplace) (= marketplace :all))
                all-marketplaces
                [marketplace])
        ;; Determine which entity types to expand
        types (if (or (nil? what) (= what :all))
                (vec all-entity-types)
                [what])
        ;; Filter to valid (mp, type) combinations
        pairs (for [mp    mps
                    etype types
                    :when (compatible? mp etype)]
                [mp etype])
        ;; Build task pairs — ingest first, materialize second (topological order)
        all-tasks (mapcat (fn [[mp etype]]
                            (make-task-pair run-id mp etype period-from period-to))
                          pairs)
        ;; Re-sort: all ingest tasks first, then all materialize tasks
        ;; This ensures topological order across the full plan vector.
        {ingest-tasks    :ingest
         materialize-tasks :materialize}
        (group-by :phase all-tasks)]
    (vec (concat ingest-tasks materialize-tasks))))

(defn persist-plan!
  "Insert each task descriptor into sync_tasks via registry/create-task!.
   Returns the input plan unchanged (caller still has the :thunk values it needs)."
  [plan]
  (doseq [task plan]
    (registry/create-task!
      {:id           (:id task)
       :run-id       (:run-id task)
       :marketplace  (when (:marketplace task) (name (:marketplace task)))
       :entity-type  (when (:entity-type task) (name (:entity-type task)))
       :phase        (when (:phase task) (name (:phase task)))
       :period-from  (:period-from task)
       :period-to    (:period-to task)
       :depends-on   (seq (:depends-on task))}))
  plan)
